### PR TITLE
Use `alembic` for database migrations

### PR DESCRIPTION
**Pull request by crazyscientist**
* Updated `README`
* Moved definition of `SQLALCHEMY_DATABASE_URL` from `database` to `config`
* Requirements
  * Added `alembic` and `uvicorn`
  * Removed frozen version strings

### CODE REVIEW

**Review by commanderprice — APPROVED** [review]
Okay, I can't say anything specific about config of Alembic, but I've run and it looks like it can generate and apply migrations👍

**Comment by crazyscientist** [comment]
> But probably you should remove existing migration in your files before merging

Well, that is the point of defining migrations. The migration in this PR represents the current data model. With future changes to the data model we will need to create more migrations (thankfully this is automated :joy:).

**Comment by commanderprice** [comment]
So, your idea is to create new migrations when there is a change in data model and to commit both? Okay, haven't thought about it

**Comment by crazyscientist** [comment]
> So, your idea is to create new migrations when there is a change in data model and to commit both? 

Exactly, I'm so used to Django, where this is the default behavior. Sorry, it did not occur to me that you might not be familiar with such a practice.

**Comment by commanderprice** [comment]
I was just thinking about using migrations as way to apply model changes to database😅

**Comment by crazyscientist** [comment]
I'm not 100% sure how alembic handles it, but Django needs the old migration files to calculate the diff for new migrations. But it feels logical that alembic would to it the same way.

And thank you for approving 🙂

**Pull request merged**
