### PR TITLE
Added event handler for removing items from attribute lists 

### LINKED ISSUE #103: Cannot remove item from attribute list
When a schema defines an attribute of type list, the dialogs for creating/updating entities provide a button to remove items from the list, but do not work.

image

### PR DESCRIPTION
**Pull request by crazyscientist**
closes #103

### CODE REVIEW

**Review by cherrywho — APPROVED** [review]
Looks good to me, thanks!

**Review by cherrywho — COMMENTED** [review]
Looks good to me! :+1:

**Review by cherrywho — APPROVED** [review]
LGTM.

**Review by frozenIceage — APPROVED** [review]
LGTM.

**Pull request merged**
